### ISSUE TITLE
This solution does not work in azure function app with async mode

### ISSUE THREAD

**Issue by sameersinha05** [jsreport/jsreport-azure-functions-starter-kit#8]
When this artifact is deployed in azure function app with configuration as "options": { "reports": { "async": true }, I am getting below error with status code 400:

TypeError: Cannot read properties of undefined (reading 'Location')
    at Reports._handleBeforeRender (/home/site/wwwroot/node_modules/@jsreport/jsreport-reports/lib/main.js:272:168)
    at async ListenerCollection.fire (/home/site/wwwroot/node_modules/@jsreport/jsreport-core/lib/shared/listenerCollection.js:157:21)
    at async MainReporter.render (/home/site/wwwroot/node_modules/@jsreport/jsreport-core/lib/main/reporter.js:433:7)
    at async module.exports (/home/site/wwwroot/HttpTrigger1/index.js:25:21)

It is able to generate report in function app when async is not set to true ("async": false)

**Comment by pofider** [comment]
Thanks. The async reports need the express extension (web server)  which is disabled in the starterkit.

Would you please describe how you plan to use async reports i azure function? I am not sure if it is a valid scenario.

**Comment by sameersinha05** [comment]
Thanks for your quick response Jan. Based on the frequency of request for report generation and the cost, I was exploring Jsreport on function app and I came across this solution on github. Now I understand because we have 3 Https calls between generation and download probably server-less (azure function app and aws lamda) might not be the right service.

Is there any documentation on how to override the "jsreport.config.json" in the jsreport docker image? We want to leverage azure blob storage for both template and report. On running container after overriding "jsreport.config.json", the azure blob storage works fine but as a part of ci-cd, if we want to override "jsreport.config.json" and push the docker image in our internal repository, is it possible?

**Comment by pofider** [comment]
> Is there any documentation on how to override the "jsreport.config.json" in the jsreport docker image?

https://jsreport.net/learn/docker#use-your-own-config-file

**Comment by sameersinha05** [comment]
Thanks Jan.
